#!/bin/bash

set -e

echo "Starting generating of global config plist"
echo "NOTE: Do not commit the generated file"

CONFIG_FILE="${SRCROOT}/../env"
if [ ! -f ${CONFIG_FILE} ]
then
    echo "WARNING: Missing global environment file, skipping generating plist"
    exit 0
fi

echo "Importing config from $CONFIG_FILE"
export $(cat $CONFIG_FILE | grep -v '^#' | xargs)

FABRIC_SECTION=""
if [ ! -z ${FABRIC_API_KEY} ] && [ ! -z ${FABRIC_BUILD_SECRET} ]
then
    echo "Found Fabric API key and secret."
    FABRIC_SECTION=$(cat << EOF
        <key>FABRIC_API_KEY</key>
        <string>$FABRIC_API_KEY</string>
        <key>FABRIC_BUILD_SECRET</key>
        <string>$FABRIC_BUILD_SECRET</string>
    )

    TEMP_API_KEY_FILE="${TEMP_DIR}/fabric.apikey"
    echo "Writing fabric api key to temp file: ${TEMP_API_KEY_FILE}"
    echo ${FABRIC_API_KEY} > ${TEMP_API_KEY_FILE}

    TEMP_BUILD_SECRET_FILE="${TEMP_DIR}/fabric.buildsecret"
    echo "Writing fabric build secret to temp file: ${TEMP_BUILD_SECRET_FILE}"
    echo ${FABRIC_BUILD_SECRET} > ${TEMP_BUILD_SECRET_FILE}
fi

BUILD_MACHINE_OVERRIDE_SECTION=""
if [ ! -z ${BUILD_MACHINE_IP_OVERRIDE} ]
then
    echo "Found build machine up override"
    BUILD_MACHINE_OVERRIDE_SECTION=$(cat << EOF
        <key>BUILD_MACHINE_IP_OVERRIDE</key>
        <string>${BUILD_MACHINE_IP_OVERRIDE}</string>
    )
fi

CONFIG_PLIST="${SRCROOT}/NewsCats/GlobalConfig-Info.plist"
echo "Writing global config plist: $CONFIG_PLIST"

cat << EOF > "${CONFIG_PLIST}"
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Auto generated by our build -->
<plist version="1.0">
<dict>
$FABRIC_SECTION
$BUILD_MACHINE_OVERRIDE_SECTION
</dict>
</plist>
EOF

